import { Container, Typography, Grid, Card, CardContent, TextField, Button, Stack, Box, MenuItem, Autocomplete, Divider } from "@mui/material";
import { useEffect, useState } from "react";
import jsPDF from "jspdf";
import { useStore } from "../store";
import { trackComplianceViewed } from "../analytics/ga";

const grades = ["K", "1st", "2nd", "3rd", "4th", "5th", "6th", "7th", "8th", "9th", "10th", "11th", "12th"];
const schoolSuggestions = [
  "Private School Affidavit School",
  "Homeloom Family Academy",
  "Sunrise Home Academy",
];

export default function Compliance() {
  const { state, updateParent } = useStore();
  const [form, setForm] = useState({
    parentName: state.parent.name || "",
    address: state.parent.address || "",
    students: state.children.map((c) => ({ name: c.name, grade: c.grade || "3rd" })),
    schoolName: "Private School Affidavit School",
  });
  const [errors, setErrors] = useState({});

  useEffect(() => {
    trackComplianceViewed();
  }, []);

  const set = (k, v) => setForm((f) => ({ ...f, [k]: v }));
  const setStudent = (i, k, v) =>
    setForm((f) => ({ ...f, students: f.students.map((s, idx) => (idx === i ? { ...s, [k]: v } : s)) }));
  const addStudent = () => setForm((f) => ({ ...f, students: [...f.students, { name: "", grade: "3rd" }] }));
  const removeStudent = (i) => setForm((f) => ({ ...f, students: f.students.filter((_, idx) => idx !== i) }));

  const validate = () => {
    const e = {};
    if (!form.parentName.trim()) e.parentName = "Required";
    if (!form.address.trim()) e.address = "Required";
    if (!form.schoolName.trim()) e.schoolName = "Required";
    if (!form.students.length || form.students.some((s) => !s.name.trim())) e.students = "All students need a name";
    setErrors(e);
    return Object.keys(e).length === 0;
  };

  const handleGenerate = () => {
    if (!validate()) return;
    updateParent({ name: form.parentName, address: form.address });
  };

  const handleDownload = () => {
    if (!validate()) return;
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text("California Private School Affidavit (PSA)", 20, 20);
    doc.setFontSize(11);
    doc.text("Generated by Homeloom", 20, 28);
    doc.line(20, 32, 190, 32);

    let y = 44;
    const row = (label, val) => {
      doc.setFont(undefined, "bold");
      doc.text(label, 20, y);
      doc.setFont(undefined, "normal");
      doc.text(String(val || "—"), 80, y);
      y += 8;
    };
    row("School Name:", form.schoolName);
    row("Parent / Administrator:", form.parentName);
    row("School Address:", form.address);
    row("School Year:", `${new Date().getFullYear()}–${new Date().getFullYear() + 1}`);

    y += 4;
    doc.setFont(undefined, "bold");
    doc.text("Students Enrolled", 20, y); y += 8;
    doc.setFont(undefined, "normal");
    form.students.forEach((s, i) => {
      doc.text(`${i + 1}. ${s.name}  —  Grade ${s.grade}`, 24, y);
      y += 7;
    });

    y += 6;
    doc.setFontSize(9);
    doc.text(
      "This document is a Homeloom-generated draft to assist with filing the official",
      20, y
    );
    doc.text(
      "California PSA at https://www.cde.ca.gov. It is not a substitute for the official filing.",
      20, y + 5
    );

    doc.save(`PSA-${form.parentName.replace(/\s+/g, "_")}.pdf`);
  };

  return (
    <Container maxWidth="lg" sx={{ py: { xs: 4, md: 6 } }}>
      <Typography variant="overline" color="primary">California · Compliance</Typography>
      <Typography variant="h4" sx={{ mt: 1, mb: 1 }}>Private School Affidavit</Typography>
      <Typography color="text.secondary" sx={{ mb: 4, maxWidth: 720 }}>
        Fill in your details and generate a PSA draft. You can download it as PDF for your records.
      </Typography>

      <Grid container spacing={3}>
        <Grid item xs={12} md={6}>
          <Card>
            <CardContent>
              <Stack spacing={2}>
                <TextField
                  label="Parent Name" required value={form.parentName}
                  onChange={(e) => set("parentName", e.target.value)}
                  error={!!errors.parentName} helperText={errors.parentName}
                />
                <TextField
                  label="Address" required value={form.address}
                  onChange={(e) => set("address", e.target.value)}
                  error={!!errors.address} helperText={errors.address}
                  multiline minRows={2}
                />
                <Autocomplete
                  freeSolo
                  options={schoolSuggestions}
                  value={form.schoolName}
                  onInputChange={(_, v) => set("schoolName", v)}
                  renderInput={(params) => (
                    <TextField {...params} label="School Name" required
                      error={!!errors.schoolName} helperText={errors.schoolName} />
                  )}
                />

                <Divider sx={{ my: 1 }}>Students</Divider>
                {form.students.map((s, i) => (
                  <Stack direction={{ xs: "column", sm: "row" }} spacing={1} key={i}>
                    <TextField
                      label={`Student ${i + 1} Name`} required value={s.name}
                      onChange={(e) => setStudent(i, "name", e.target.value)}
                      sx={{ flex: 2 }}
                    />
                    <TextField
                      select label="Grade" value={s.grade}
                      onChange={(e) => setStudent(i, "grade", e.target.value)}
                      sx={{ flex: 1, minWidth: 100 }}
                    >
                      {grades.map((g) => <MenuItem key={g} value={g}>{g}</MenuItem>)}
                    </TextField>
                    {form.students.length > 1 && (
                      <Button onClick={() => removeStudent(i)} color="inherit">Remove</Button>
                    )}
                  </Stack>
                ))}
                {errors.students && <Typography color="error" variant="caption">{errors.students}</Typography>}
                <Button onClick={addStudent} variant="text" sx={{ alignSelf: "flex-start" }}>+ Add student</Button>

                <Stack direction="row" spacing={2} sx={{ pt: 1 }}>
                  <Button variant="contained" onClick={handleGenerate}>Generate PSA</Button>
                  <Button variant="outlined" onClick={handleDownload}>Download PDF</Button>
                </Stack>
              </Stack>
            </CardContent>
          </Card>
        </Grid>

        <Grid item xs={12} md={6}>
          <Card sx={{ position: { md: "sticky" }, top: 80 }}>
            <CardContent>
              <Typography variant="overline" color="text.secondary">Preview</Typography>
              <Typography variant="h5" sx={{ mt: 1, mb: 2 }}>California PSA Draft</Typography>
              <Box sx={{ p: 3, bgcolor: "secondary.main", borderRadius: 2, fontFamily: "Roboto, sans-serif" }}>
                <Typography variant="subtitle2" color="text.secondary">School Year</Typography>
                <Typography sx={{ mb: 2 }}>{new Date().getFullYear()}–{new Date().getFullYear() + 1}</Typography>

                <Typography variant="subtitle2" color="text.secondary">School Name</Typography>
                <Typography sx={{ mb: 2 }}>{form.schoolName || "—"}</Typography>

                <Typography variant="subtitle2" color="text.secondary">Parent / Administrator</Typography>
                <Typography sx={{ mb: 2 }}>{form.parentName || "—"}</Typography>

                <Typography variant="subtitle2" color="text.secondary">Address</Typography>
                <Typography sx={{ mb: 2, whiteSpace: "pre-wrap" }}>{form.address || "—"}</Typography>

                <Typography variant="subtitle2" color="text.secondary">Students</Typography>
                {form.students.map((s, i) => (
                  <Typography key={i}>{i + 1}. {s.name || "—"} · Grade {s.grade}</Typography>
                ))}
              </Box>
              <Typography variant="caption" color="text.secondary" sx={{ display: "block", mt: 2 }}>
                Draft only. Final filing happens on the official California Department of Education site.
              </Typography>
            </CardContent>
          </Card>
        </Grid>
      </Grid>
    </Container>
  );
}
